### ISSUE TITLE
Process cleanup on fail

### ISSUE THREAD

**Issue by mpoquet** [simgrid/remote-simgrid#8]
Currently, processes are not always cleaned up when a test fails.

**Comment by mquinson** [comment]
On Fri, Feb 16, 2018 at 08:28:47AM -0800, Millian Poquet wrote:
> Currently, processes are not always cleaned up when a test fails.

This is not really specific here. It will be hard to see when this
point can be closed if it's that open.

**Comment by mpoquet** [comment]
This issue had multiple sources:
- tesh did not clean subprocesses properly.  
  This should be fixed as simgrid/simgrid@d93440cdf.
- most tests had an unset timeout.  
  This should be fixed as 48723e0.
